import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const TRANSLATIONS = {
  en: {
    // Nav & Common
    appName: "Rural Employment Hub",
    welcome: "Welcome",
    logout: "Logout",
    dashboard: "Dashboard",
    attendance: "Attendance",
    assignments: "Work Assignments",
    payments: "DBT Wage Credits",
    profile: "Worker Profile",
    assistant: "AI Assistant",
    notifications: "Notifications",
    settings: "Settings",
    language: "Language",

    // Dashboard
    empPortalTitle: "Gram Panchayat Muster & DBT Portal",
    wagesCredited: "Wages Credited (DBT)",
    assignedProjects: "Assigned Projects",
    musterStatus: "Muster Work Status",
    recentWageCredits: "Recent DBT Wage Credits",
    workerDetails: "Worker Profile Details",
    employeeId: "Employee ID",
    gramPanchayat: "Gram Panchayat",
    state: "State",
    district: "District",
    mandal: "Mandal / Block",
    village: "Village",
    phone: "Mobile Phone",
    bankAccount: "Bank Account",
    bankVerifiedBadge: "DBT OTP Verified",
    bankPendingBadge: "OTP Pending",
    editBank: "Edit Profile & Bank Account",
    unreadAlerts: "Unread Alerts",
    viewAll: "View All",

    // Biometric & Muster Attendance History
    attendanceMusterHistory: "Attendance Muster History",
    attendanceHistorySub: "Track your monthly attendance, verified shifts, and daily working hours.",
    downloadStatement: "Download Statement",
    daysPresent: "Days Present",
    daysAbsent: "Days Absent",
    halfDays: "Half Days",
    sanctionedLeave: "Sanctioned Leave",
    attendanceRate: "Attendance Rate",
    selectPeriod: "Select Period",
    date: "Date",
    status: "Status",
    inOutTime: "In / Out Time",
    hours: "Hours",
    verification: "Verification",
    locationRemarks: "Location / Remarks",
    dailyAttendance: "Daily Attendance Verification",
    musterCheckinSub: "Mark your daily muster check-in via Face Recognition or Fingerprint.",
    biometricStation: "Biometric Verification Station",
    faceIdScan: "Face Recognition",
    fingerprintScan: "Fingerprint Scan",
    qrScan: "Muster QR Code",
    positionFace: "Position Face in Camera Frame",
    cameraInstructions: "Ensure adequate lighting. Anti-spoofing algorithm checks for live face.",
    placeFinger: "Place Thumb on Fingerprint Sensor",
    fingerInstructions: "Press firmly on the biometric scanner pad for identity verification.",
    confirmCheckIn: "Confirm Morning Check-In",
    confirmCheckOut: "Record Shift Check-Out",
    attendanceVerified: "Attendance Verified for Today",
    verifyingIdentity: "Verifying identity & anti-spoofing checks...",

    // Assignments
    ruralWorkAssignments: "Rural Work Assignments",
    assignmentsSub: "View sanctioned community infrastructure projects and muster allocation.",
    myProjects: "My Allocated Projects",
    activeProjects: "Village Active Projects",
    acceptWork: "Accept Work",
    declineWork: "Decline",
    accepted: "Accepted",
    assigned: "Assigned",
    completed: "Completed",
    dailyWage: "Daily Wage",
    duration: "Duration",
    location: "Location",

    // Bank Details & OTP
    bankTitle: "Bank Account for Direct Benefit Transfer (DBT)",
    bankSub: "Ensure account details match your Aadhaar name exactly for secure wage disbursals.",
    bankName: "Bank Name",
    accountHolder: "Account Holder Name",
    accountNumber: "Account Number",
    ifscCode: "IFSC Code",
    sendBankOtp: "Send Bank Verification OTP",
    verifyConfirmBank: "Verify OTP & Confirm Bank",
    otpSentMsg: "OTP sent to registered mobile number",
    enterOtp: "Enter 6-digit OTP",
    otpPlaceholder: "6-digit OTP",
    resendBankOtpIn: "Resend OTP in",
    verifiedSuccess: "Bank details verified and confirmed!",

    // Employee Login
    signInWithMobile: "Sign in with your mobile number",
    otpSentTo: "OTP sent to +91",
    mobileNumberLabel: "Mobile Phone Number",
    mobilePlaceholder: "e.g. 9876543210",
    sendOtpBtn: "Send Verification OTP",
    enterOtpLabel: "Enter 6-Digit OTP",
    enterOtpPlaceholder: "Enter 6-digit OTP",
    verifySignInBtn: "Verify & Sign In",
    changePhone: "Change Number",
    resendOtpIn: "Resend OTP in",
    resendOtp: "Resend OTP",
    home: "Home",
    backToHome: "Back to Home",
    newHere: "New worker?",
    register: "Register here",
    validPhoneError: "Please enter a valid 10-digit Indian mobile number.",
    validOtpError: "Please enter the 6-digit OTP.",
    workerLoginPortal: "Rural Worker Portal",
    adminPortalLink: "Admin Login",
    selectLanguage: "Choose Language",
    chooseLoginLanguage: "Select Language / భాష / भाषा",
    loginSubtext: "Access your daily muster, work assignments, and DBT wage credits.",
    mobileHelper: "A 6-digit OTP will be sent to your Aadhaar-linked mobile.",
    otpHelper: "Enter the code sent to your phone to securely log in.",
    officialGovtPortal: "Official Gram Panchayat & DBT Portal",
    mgnregaTagline: "MGNREGA Wage Disbursal & Muster Tracking",
    needHelp: "Need help? Contact Gram Panchayat",

    // Gramin AI Assistant
    graminAiAssistant: "Gramin AI Assistant",
    active247: "ACTIVE 24/7",
    assistantTagline: "Instant guidance on muster rolls, DBT payments, and welfare schemes",
    newChat: "New Chat",
    assistantWelcome: "Namaste {name}! I am your Rural Employment Hub Assistant. I can help answer questions about your attendance, wage payments, work assignments, and rural welfare schemes. How can I help you today?",
    assistantFreshWelcome: "Namaste {name}! Started a fresh conversation. How may I assist you now?",
    promptAttendance: "How do I mark daily attendance?",
    promptSalary: "When will my salary be credited?",
    promptSchemes: "What schemes are available for rural workers?",
    promptWageCalc: "How is my daily wage calculated?",
    chatPlaceholder: "Ask about payments, muster roll, attendance, or schemes...",
    processingQuery: "I am processing your query.",

    // Language names
    enName: "English",
    teName: "తెలుగు (Telugu)",
    hiName: "हिंदी (Hindi)",
  },

  te: {
    // Nav & Common
    appName: "గ్రామీణ ఉపాధి కేంద్రం",
    welcome: "స్వాగతం",
    logout: "లాగ్ అవుట్",
    dashboard: "డాష్‌బోర్డ్",
    attendance: "హాజరు",
    assignments: "పని కేటాయింపులు",
    payments: "డీబీటీ వేతన చెల్లింపులు",
    profile: "కార్మికుడి వివరాలు",
    assistant: "AI సహాయకుడు",
    notifications: "నోటిఫికేషన్లు",
    settings: "సెట్టింగులు",
    language: "భాష",

    // Dashboard
    empPortalTitle: "గ్రామ పంచాయతీ మస్టర్ & డీబీటీ పోర్టల్",
    wagesCredited: "జమ అయిన వేతనం (DBT)",
    assignedProjects: "కేటాయించిన పనులు",
    musterStatus: "మస్టర్ పని స్థితి",
    recentWageCredits: "ఇటీవలి డీబీటీ వేతన క్రెడిట్లు",
    workerDetails: "కార్మికుడి ప్రొఫైల్ వివరాలు",
    employeeId: "ఎంప్లాయ్ ఐడీ",
    gramPanchayat: "గ్రామ పంచాయతీ",
    state: "రాష్ట్రం",
    district: "జిల్లా",
    mandal: "మండలం",
    village: "గ్రామం",
    phone: "మొబైల్ ఫోన్",
    bankAccount: "బ్యాంక్ ఖాతా",
    bankVerifiedBadge: "OTP ధృవీకరించబడింది",
    bankPendingBadge: "OTP పెండింగ్",
    editBank: "ప్రొఫైల్ & బ్యాంక్ వివరాలు మార్చండి",
    unreadAlerts: "చదవని సమాచారం",
    viewAll: "అన్నీ చూడండి",

    // Biometric & Muster Attendance History
    attendanceMusterHistory: "హాజరు మస్టర్ రికార్డు",
    attendanceHistorySub: "మీ నెలవారీ హాజరు, ధృవీకరించబడిన షిఫ్టులు మరియు పని గంటలను ట్రాక్ చేయండి.",
    downloadStatement: "స్టేట్‌మెంట్ డౌన్‌లోడ్ చేయండి",
    daysPresent: "హాజరైన రోజులు",
    daysAbsent: "హాజరుకాని రోజులు",
    halfDays: "హాఫ్ డేస్",
    sanctionedLeave: "మంజూరైన సెలవులు",
    attendanceRate: "హాజరు శాతం",
    selectPeriod: "కాలాన్ని ఎంచుకోండి",
    date: "తేదీ",
    status: "స్థితి",
    inOutTime: "ఇన్ / అవుట్ సమయం",
    hours: "పని గంటలు",
    verification: "ధృవీకరణ",
    locationRemarks: "స్థలం / వివరాలు",
    dailyAttendance: "రోజువారీ హాజరు ధృవీకరణ",
    musterCheckinSub: "ఫేస్ రికగ్నిషన్ లేదా వేలిముద్ర స్కానింగ్ ద్వారా మీ రోజువారీ హాజరు నమోదు చేయండి.",
    biometricStation: "బయోమెట్రిక్ వెరిఫికేషన్ స్టేషన్",
    faceIdScan: "ముఖ గుర్తింపు (Face ID)",
    fingerprintScan: "వేలిముద్ర స్కాన్ (Fingerprint)",
    qrScan: "మస్టర్ క్యూఆర్ కోడ్",
    positionFace: "కెమెరా ఫ్రేమ్‌లో ముఖాన్ని ఉంచండి",
    cameraInstructions: "సరైన వెలుతురు ఉండేలా చూసుకోండి. నిజమైన ముఖాన్ని ధృవీకరిస్తుంది.",
    placeFinger: "సెన్సార్‌పై బొటనవేలును ఉంచండి",
    fingerInstructions: "గుర్తింపు ధృవీకరణ కోసం స్కానర్ ప్యాడ్‌పై గట్టిగా నొక్కండి.",
    confirmCheckIn: "ఉదయం చెక్-ఇన్ నిర్ధారించండి",
    confirmCheckOut: "షిఫ్ట్ చెక్-అవుట్ నమోదు చేయండి",
    attendanceVerified: "ఈ రోజు హాజరు ధృవీకరించబడింది",
    verifyingIdentity: "గుర్తింపు మరియు హాజరు ధృవీకరించబడుతోంది...",

    // Assignments
    ruralWorkAssignments: "గ్రామీణ ఉపాధి పనులు",
    assignmentsSub: "మంజూరైన గ్రామీణ మౌలిక సదుపాయాల ప్రాజెక్టులు మరియు మస్టర్ కేటాయింపులను వీక్షించండి.",
    myProjects: "నాకు కేటాయించిన ప్రాజెక్టులు",
    activeProjects: "గ్రామంలో కొనసాగుతున్న పనులు",
    acceptWork: "పనిని అంగీకరించండి",
    declineWork: "తిరస్కరించండి",
    accepted: "స్వీకరించబడింది",
    assigned: "కేటాయించబడింది",
    completed: "పూర్తయింది",
    dailyWage: "రోజువారీ వేతనం",
    duration: "వ్యవధి",
    location: "పని ప్రదేశం",

    // Bank Details & OTP
    bankTitle: "ప్రత్యక్ష నగదు బదిలీ (DBT) కోసం బ్యాంక్ ఖాతా",
    bankSub: "వేతనాల చెల్లింపులో అంతరాయం లేకుండా ఉండటానికి మీ ఆధార్ పేరుతో సరిపోలేలా చూసుకోండి.",
    bankName: "బ్యాంక్ పేరు",
    accountHolder: "ఖాతాదారుని పేరు",
    accountNumber: "ఖాతా సంఖ్య",
    ifscCode: "IFSC కోడ్",
    sendBankOtp: "బ్యాంక్ ధృవీకరణ OTP పంపండి",
    verifyConfirmBank: "OTP ధృవీకరించి ఖాతాను నిర్ధారించండి",
    otpSentMsg: "రిజిస్టర్డ్ మొబైల్ నంబర్‌కు OTP పంపబడింది",
    enterOtp: "6 అంకెల OTP నమోదు చేయండి",
    otpPlaceholder: "6-అంకెల OTP",
    resendBankOtpIn: "మళ్లీ OTP పంపడానికి సమయం",
    verifiedSuccess: "బ్యాంక్ ఖాతా విజయవంతంగా ధృవీకరించబడింది!",

    // Employee Login
    signInWithMobile: "మీ మొబైల్ నంబర్‌తో లాగిన్ అవ్వండి",
    otpSentTo: "OTP పంపబడింది: +91",
    mobileNumberLabel: "మొబైల్ ఫోన్ నంబర్",
    mobilePlaceholder: "ఉదా. 9876543210",
    sendOtpBtn: "ధృవీకరణ OTP పంపండి",
    enterOtpLabel: "6 అంకెల OTP నమోదు చేయండి",
    enterOtpPlaceholder: "6-అంకెల OTP రాయండి",
    verifySignInBtn: "ధృవీకరించి లాగిన్ అవ్వండి",
    changePhone: "నంబర్ మార్చండి",
    resendOtpIn: "మళ్లీ OTP పంపడానికి",
    resendOtp: "మళ్లీ OTP పంపండి",
    home: "హోమ్",
    backToHome: "హోమ్ పేజీకి వెళ్ళండి",
    newHere: "కొత్త కార్మికులా?",
    register: "ఇక్కడ నమోదు చేసుకోండి",
    validPhoneError: "దయచేసి సరైన 10 అంకెల భారతీయ మొబైల్ నంబర్ నమోదు చేయండి.",
    validOtpError: "దయచేసి 6 అంకెల OTP నమోదు చేయండి.",
    workerLoginPortal: "గ్రామీణ కార్మికుల పోర్టల్",
    adminPortalLink: "అడ్మిన్ లాగిన్",
    selectLanguage: "భాషను ఎంచుకోండి",
    chooseLoginLanguage: "భాషను ఎంచుకోండి / Select Language",
    loginSubtext: "మీ రోజువారీ మస్టర్, పని కేటాయింపులు మరియు డీబీటీ వేతన క్రెడిట్‌లను వీక్షించండి.",
    mobileHelper: "మీ ఆధార్ లింక్ చేయబడిన మొబైల్ నంబర్‌కు 6 అంకెల OTP పంపబడుతుంది.",
    otpHelper: "సురక్షితంగా లాగిన్ కావడానికి మీ మొబైల్‌కు వచ్చిన OTP ని నమోదు చేయండి.",
    officialGovtPortal: "అధికారిక గ్రామ పంచాయతీ & DBT పోర్టల్",
    mgnregaTagline: "ఉపాధి హామీ పథకం వేతన చెల్లింపు & మస్టర్ ట్రాకింగ్",
    needHelp: "సహాయం కావాలా? గ్రామ పంచాయతీని సంప్రదించండి",

    // Gramin AI Assistant
    graminAiAssistant: "గ్రామీణ AI సహాయకుడు",
    active247: "24/7 అందుబాటులో ఉంది",
    assistantTagline: "మస్టర్ రికార్డులు, డీబీటీ చెల్లింపులు మరియు సంక్షేమ పథకాలపై తక్షణ మార్గదర్శకత్వం",
    newChat: "కొత్త సంభాషణ",
    assistantWelcome: "నమస్తే {name}! నేను మీ గ్రామీణ ఉపాధి సహాయకుడిని. మీ హాజరు, వేతన చెల్లింపులు, పని కేటాయింపులు మరియు సంక్షేమ పథకాల గురించి సమాధానాలు ఇవ్వగలను. నేను మీకు ఎలా సహాయపడగలను?",
    assistantFreshWelcome: "నమస్తే {name}! కొత్త సంభాషణ ప్రారంభించబడింది. ఇప్పుడు మీకు ఏ విధమైన సహాయం కావాలి?",
    promptAttendance: "రోజువారీ హాజరు ఎలా నమోదు చేయాలి?",
    promptSalary: "నా వేతనం ఎప్పుడు ఖాతాలో జమ అవుతుంది?",
    promptSchemes: "గ్రామీణ కార్మికులకు ఏ పథకాలు అందుబాటులో ఉన్నాయి?",
    promptWageCalc: "నా రోజువారీ వేతనం ఎలా లెక్కించబడుతుంది?",
    chatPlaceholder: "చెల్లింపులు, మస్టర్ రోల్, హాజరు లేదా పథకాల గురించి అడగండి...",
    processingQuery: "మీ సమాధానాన్ని సిద్ధం చేస్తున్నాము...",

    // Language names
    enName: "English",
    teName: "తెలుగు (Telugu)",
    hiName: "हिंदी (Hindi)",
  },

  hi: {
    // Nav & Common
    appName: "ग्रामीण रोजगार केंद्र",
    welcome: "स्वागत है",
    logout: "लॉग आउट",
    dashboard: "डैशबोर्ड",
    attendance: "उपस्थिति",
    assignments: "कार्य आवंटन",
    payments: "डीबीटी मजदूरी भुगतान",
    profile: "श्रमिक प्रोफ़ाइल",
    assistant: "एआई सहायक",
    notifications: "सूचनाएं",
    settings: "सेटिंग्स",
    language: "भाषा",

    // Dashboard
    empPortalTitle: "ग्राम पंचायत मस्टर एवं डीबीटी पोर्टल",
    wagesCredited: "जमा मजदूरी (DBT)",
    assignedProjects: "आवंटित कार्य",
    musterStatus: "मस्टर कार्य स्थिति",
    recentWageCredits: "हालिया डीबीटी मजदूरी क्रेडिट",
    workerDetails: "श्रमिक प्रोफ़ाइल विवरण",
    employeeId: "कर्मचारी आईडी",
    gramPanchayat: "ग्राम पंचायत",
    state: "राज्य",
    district: "जिला",
    mandal: "प्रखंड / मंडल",
    village: "गांव",
    phone: "मोबाइल नंबर",
    bankAccount: "बैंक खाता",
    bankVerifiedBadge: "OTP द्वारा सत्यापित",
    bankPendingBadge: "सत्यापन बाकी",
    editBank: "प्रोफ़ाइल और बैंक विवरण अपडेट करें",
    unreadAlerts: "अपठित सूचनाएं",
    viewAll: "सभी देखें",

    // Biometric & Muster Attendance History
    attendanceMusterHistory: "उपस्थिति मस्टर इतिहास",
    attendanceHistorySub: "अपनी मासिक उपस्थिति, सत्यापित शिफ्ट और दैनिक कार्य घंटों को ट्रैक करें।",
    downloadStatement: "स्टेटमेंट डाउनलोड करें",
    daysPresent: "उपस्थित दिन",
    daysAbsent: "अनुपस्थित दिन",
    halfDays: "आधा दिन",
    sanctionedLeave: "स्वीकृत अवकाश",
    attendanceRate: "उपस्थिति दर",
    selectPeriod: "अवधि चुनें",
    date: "तारीख",
    status: "स्थिति",
    inOutTime: "इन / आउट समय",
    hours: "घंटे",
    verification: "सत्यापन",
    locationRemarks: "स्थान / विवरण",
    dailyAttendance: "दैनिक उपस्थिति सत्यापन",
    musterCheckinSub: "चेहरा पहचान (Face Recognition) या अंगूठे के निशान से उपस्थिति दर्ज करें।",
    biometricStation: "बायोमेट्रिक सत्यापन स्टेशन",
    faceIdScan: "चेहरा पहचान (Face ID)",
    fingerprintScan: "फिंगरप्रिंट स्कैन (Thumb)",
    qrScan: "मस्टर क्यूआर कोड",
    positionFace: "कैमरे के सामने चेहरा रखें",
    cameraInstructions: "पर्याप्त रोशनी सुनिश्चित करें। एंटी-स्पूफिंग तकनीक से लाइव चेहरा सत्यापित होता है।",
    placeFinger: "सेंसर पर अंगूठा रखें",
    fingerInstructions: "पहचान सत्यापन के लिए बायोमेट्रिक स्कैनर पर मजबूती से दबाएं।",
    confirmCheckIn: "प्रातः उपस्थिति दर्ज करें",
    confirmCheckOut: "शिफ्ट समाप्ति दर्ज करें",
    attendanceVerified: "आज की उपस्थिति सत्यापित हो गई है",
    verifyingIdentity: "पहचान और बायोमेट्रिक सत्यापन प्रगति पर है...",

    // Assignments
    ruralWorkAssignments: "ग्रामीण कार्य आवंटन",
    assignmentsSub: "स्वीकृत सामुदायिक विकास परियोजनाएं और मस्टर आवंटन देखें।",
    myProjects: "मुझे आवंटित परियोजनाएं",
    activeProjects: "ग्राम में सक्रिय कार्य",
    acceptWork: "कार्य स्वीकार करें",
    declineWork: "अस्वीकार करें",
    accepted: "स्वीकृत",
    assigned: "आवंटित",
    completed: "पूर्ण",
    dailyWage: "दैनिक मजदूरी",
    duration: "अवधि",
    location: "कार्य स्थल",

    // Bank Details & OTP
    bankTitle: "प्रत्यक्ष लाभ अंतरण (DBT) हेतु बैंक खाता",
    bankSub: "मजदूरी समय पर पाने के लिए बैंक विवरण आपके आधार नाम से बिल्कुल मेल खाना चाहिए।",
    bankName: "बैंक का नाम",
    accountHolder: "खाताधारक का नाम",
    accountNumber: "खाता संख्या",
    ifscCode: "IFSC कोड",
    sendBankOtp: "बैंक सत्यापन OTP भेजें",
    verifyConfirmBank: "OTP सत्यापित कर खाता सुरक्षित करें",
    otpSentMsg: "पंजीकृत मोबाइल नंबर पर OTP भेज दिया गया है",
    enterOtp: "6 अंकों का OTP दर्ज करें",
    otpPlaceholder: "6-अंकों का OTP",
    resendBankOtpIn: "पुनः OTP भेजें",
    verifiedSuccess: "बैंक खाता सफलतापूर्वक सत्यापित एवं डीबीटी से जुड़ गया!",

    // Employee Login
    signInWithMobile: "अपने मोबाइल नंबर से लॉगिन करें",
    otpSentTo: "OTP भेजा गया: +91",
    mobileNumberLabel: "मोबाइल फोन नंबर",
    mobilePlaceholder: "उदा. 9876543210",
    sendOtpBtn: "सत्यापन OTP भेजें",
    enterOtpLabel: "6 अंकों का OTP दर्ज करें",
    enterOtpPlaceholder: "6 अंकों का OTP दर्ज करें",
    verifySignInBtn: "सत्यापित कर लॉगिन करें",
    changePhone: "नंबर बदलें",
    resendOtpIn: "पुनः OTP भेजें",
    resendOtp: "पुनः OTP भेजें",
    home: "होम",
    backToHome: "मुख्य पृष्ठ पर वापस जाएं",
    newHere: "नए श्रमिक?",
    register: "यहाँ पंजीकरण करें",
    validPhoneError: "कृपया वैध 10 अंकों का भारतीय मोबाइल नंबर दर्ज करें।",
    validOtpError: "कृपया 6 अंकों का OTP दर्ज करें।",
    workerLoginPortal: "ग्रामीण श्रमिक पोर्टल",
    adminPortalLink: "व्यवस्थापक लॉगिन",
    selectLanguage: "भाषा चुनें",
    chooseLoginLanguage: "भाषा चुनें / Select Language",
    loginSubtext: "अपनी दैनिक उपस्थिति मस्टर, कार्य आवंटन और डीबीटी मजदूरी विवरण देखें।",
    mobileHelper: "आपके आधार से जुड़े मोबाइल नंबर पर 6 अंकों का OTP भेजा जाएगा।",
    otpHelper: "सुरक्षित लॉगिन के लिए अपने मोबाइल पर प्राप्त OTP दर्ज करें।",
    officialGovtPortal: "आधिकारिक ग्राम पंचायत एवं DBT पोर्टल",
    mgnregaTagline: "मनरेगा मजदूरी भुगतान एवं मस्टर ट्रैकिंग",
    needHelp: "सहायता चाहिए? ग्राम पंचायत से संपर्क करें",

    // Gramin AI Assistant
    graminAiAssistant: "ग्रामीण एआई सहायक",
    active247: "24/7 सक्रिय",
    assistantTagline: "मस्टर रोल, डीबीटी भुगतान और कल्याणकारी योजनाओं पर त्वरित मार्गदर्शन",
    newChat: "नई बातचीत",
    assistantWelcome: "नमस्ते {name}! मैं आपका ग्रामीण रोजगार सहायक हूँ। मैं आपकी उपस्थिति, मजदूरी भुगतान, कार्य आवंटन और ग्रामीण योजनाओं से जुड़े सवालों में मदद कर सकता हूँ। मैं आपकी क्या सहायता कर सकता हूँ?",
    assistantFreshWelcome: "नमस्ते {name}! नई बातचीत शुरू की गई है। अब मैं आपकी क्या सहायता कर सकता हूँ?",
    promptAttendance: "दैनिक उपस्थिति कैसे दर्ज करें?",
    promptSalary: "मेरी मजदूरी खाते में कब जमा होगी?",
    promptSchemes: "ग्रामीण श्रमिकों के लिए कौन सी योजनाएं उपलब्ध हैं?",
    promptWageCalc: "मेरी दैनिक मजदूरी की गणना कैसे होती है?",
    chatPlaceholder: "भुगतान, मस्टर रोल, उपस्थिति या योजनाओं के बारे में पूछें...",
    processingQuery: "आपके सवाल का जवाब तैयार किया जा रहा है...",

    // Language names
    enName: "English",
    teName: "తెలుగు (Telugu)",
    hiName: "हिंदी (Hindi)",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(
    localStorage.getItem("reh_language") || "en"
  );

  const setLanguage = (lang) => {
    if (TRANSLATIONS[lang]) {
      setLanguageState(lang);
      localStorage.setItem("reh_language", lang);
    }
  };

  const t = (key, fallback = "") => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en?.[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: ["en", "te", "hi"] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
